import { NextRequest, NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { buildOwnerStatements } from "@/lib/tax";
import { formatMYR } from "@/lib/format";
import { getSessionUser } from "@/lib/auth";
import { visibleOwnerIds } from "@/lib/access";

export const dynamic = "force-dynamic";

/**
 * Generate a downloadable e-Filing (LHDN) rental income statement PDF for an
 * owner + tax year. POST with { ownerId, year }. Property managers can only
 * export statements for owners they are tied to.
 */
export async function POST(req: NextRequest) {
  const me = await getSessionUser();
  if (!me) return NextResponse.json({ error: "Unauthorized." }, { status: 401 });

  const body = await req.json().catch(() => ({}));
  const ownerId = typeof body.ownerId === "string" ? body.ownerId : "";
  const year = Number(body.year);

  const ownerScope = await visibleOwnerIds(me);
  const statements = await buildOwnerStatements(ownerScope);
  const owner = statements.find((s) => s.id === ownerId);
  if (!owner) {
    return NextResponse.json({ error: "Owner not found." }, { status: 404 });
  }
  const yr = owner.years.find((y) => y.year === year);
  if (!yr) {
    return NextResponse.json({ error: `No tax data for ${year}.` }, { status: 404 });
  }

  const doc = new PDFDocument({ size: "A4", margin: 48 });
  const buffers: Uint8Array[] = [];
  doc.on("data", (chunk: Uint8Array) => buffers.push(chunk));
  const done = new Promise<void>((resolve) => doc.on("end", resolve));

  const PRIMARY = "#1d4ed8";
  const MUTED = "#64748b";

  // Header
  doc.rect(0, 0, doc.page.width, 110).fill("#0f172a");
  doc.fillColor("#ffffff").fontSize(20).font("Helvetica-Bold").text("AssetHub — Rental Income Statement", 48, 32);
  doc.fontSize(11).font("Helvetica").fillColor("#93c5fd").text("For e-Filing with LHDN (Form BE — Part C)", 48, 62);

  doc.y = 130;
  doc.fillColor("#0f172a").fontSize(14).font("Helvetica-Bold").text(`Tax Year: ${yr.year}`);
  doc.moveDown(0.4);
  doc.fontSize(11).font("Helvetica").fillColor("#334155").text(`Owner: ${owner.name}`);
  doc.text(`IC / Passport: ${owner.icNumber ?? "—"}`);
  doc.text(`Net Taxable Rental Income (Year of Assessment ${yr.year}): ${formatMYR(yr.totalNet)}`);
  doc.moveDown(1);

  const startY = doc.y;
  const rowH = 22;
  const colX = { prop: 48, share: 200, gross: 290, exp: 380, net: 460 };
  const pageW = doc.page.width - 96;

  // Table header
  doc.font("Helvetica-Bold").fontSize(10).fillColor("#ffffff");
  doc.rect(48, startY, pageW, rowH).fill(PRIMARY);
  doc.text("Property", colX.prop + 8, startY + 6);
  doc.text("Share", colX.share + 8, startY + 6, { width: 70 });
  doc.text("Gross (RM)", colX.gross, startY + 6, { width: 80, align: "right" });
  doc.text("Expenses (RM)", colX.exp, startY + 6, { width: 80, align: "right" });
  doc.text("Net (RM)", colX.net, startY + 6, { width: 80, align: "right" });

  let y = startY + rowH;
  const rows = yr.properties.length > 0 ? yr.properties : [];

  if (rows.length === 0) {
    doc.font("Helvetica").fontSize(10).fillColor("#64748b");
    doc.text("No rental properties with income recorded for this year.", 56, y + 8);
  }

  rows.forEach((p, i) => {
    if (y > doc.page.height - 80) {
      doc.addPage();
      y = 48;
    }
    doc.font("Helvetica").fontSize(10);
    doc.fillColor(i % 2 === 0 ? "#ffffff" : "#f1f5f9");
    doc.rect(48, y, pageW, rowH).fill(i % 2 === 0 ? "#ffffff" : "#f1f5f9");
    doc.fillColor("#0f172a");
    doc.text(p.name, colX.prop + 8, y + 6, { width: 130 });
    doc.text(`${p.sharePercent}%`, colX.share + 8, y + 6, { width: 70 });
    doc.text(formatMYR(p.gross), colX.gross, y + 6, { width: 80, align: "right" });
    doc.text(formatMYR(p.expenses), colX.exp, y + 6, { width: 80, align: "right" });
    doc.text(formatMYR(p.net), colX.net, y + 6, { width: 80, align: "right" });

    // Expense detail lines under each property.
    let ey = y + rowH;
    p.expenseItems.forEach((e) => {
      if (ey > doc.page.height - 60) {
        doc.addPage();
        ey = 48;
      }
      doc.fillColor("#64748b").fontSize(8.5);
      doc.text(`   − ${e.description} (${e.category}): ${formatMYR(e.amount)}`, colX.exp - 132, ey + 3, { width: 300 });
      ey += 13;
    });
    y = Math.max(y + rowH, ey + 2);
  });

  doc.moveDown(1);
  doc.font("Helvetica-Bold").fontSize(11).fillColor("#0f172a");
  doc.text(`Total Net Taxable Rental Income: ${formatMYR(yr.totalNet)}`);

  doc.moveDown(1.5);
  doc.font("Helvetica").fontSize(9).fillColor(MUTED).text(
    "Generated by AssetHub. Expenses are verified against receipts retained in the document vault.",
    48,
    doc.page.height - 40,
  );

  doc.end();
  await done;
  const pdf = Buffer.concat(buffers);

  return new NextResponse(new Uint8Array(pdf), {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="efiling-${owner.name.replace(/[^a-zA-Z0-9]+/g, "-")}-${year}.pdf"`,
    },
  });
}
